[package]
name = "tock"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
chrono-tz = "0.5.1"
signal-hook = "0.1.9"
structopt = "0.2.16"
termion = "1.5.2"
libc = "0.2.58"

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
