[package]
name = "tock"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[features]
default = ["timezone"]
timezone = ["chrono-tz"]

[dependencies]
chrono = "0.4.6"
chrono-tz = { version = "0.5.1", optional = true }
structopt = "0.2.16"
libc = "0.2.58"

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
